########################################################################################################
##                                                                                                    ##
## В плагине есть 2 локальных плейсхолдера %message% и %sender% они обрабатываются только в broadcast ##
## %message% - отправленное сообщение | %sender% - имя отправителя                                    ##
##                                                                                                    ##
########################################################################################################
no-args: '&cВведите сообщение.'
broadcast: '&#86f016[Объявление] &f%message% &#86f016[Автор: %sender%&#86f016]'
config-reload: '&bКонфигурация перезагружена'
no-permission: '&cУ вас нет разрешения не выполнение данной команды'